name: Go

on:
  push:
    branches: [ release* ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: New Scan Command
      run: go list -mod=mod -deps -json all

    - name: Old Scan Command
      run: go list -deps -json all
      
    - name: Build
      run: go build -v ./...



